In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df  = pd.read_csv('emails.csv')

In [4]:
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [5]:
df.shape

(5728, 2)

In [6]:
df['spam'].value_counts()

spam
0    4360
1    1368
Name: count, dtype: int64

In [7]:
df.isnull().sum()

text    0
spam    0
dtype: int64

In [8]:
x = df.text.values

In [9]:
y = df.spam.values

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=.2,random_state=1)

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

In [13]:
cv = CountVectorizer()

In [14]:
x_train = cv.fit_transform(xtrain)

In [15]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [16]:
from sklearn.naive_bayes import MultinomialNB

In [17]:
model = MultinomialNB()

In [18]:
model.fit(x_train,ytrain)

MultinomialNB()

In [19]:
x_test = cv.transform(xtest)

In [20]:
x_test.toarray()

array([[ 0, 12,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0]], dtype=int64)

In [21]:
model.score(x_test,ytest)

0.9947643979057592

In [22]:
model.predict(x_test)

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [23]:
pred = model.predict(x_test)

In [24]:
from sklearn.metrics import accuracy_score

In [25]:
accuracy_score(ytest,pred)

0.9947643979057592

In [26]:
from sklearn.metrics import confusion_matrix

In [27]:
confusion_matrix(ytest,pred)

array([[874,   2],
       [  4, 266]], dtype=int64)

In [28]:
from sklearn.metrics import classification_report

In [30]:
print(classification_report(ytest,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       876
           1       0.99      0.99      0.99       270

    accuracy                           0.99      1146
   macro avg       0.99      0.99      0.99      1146
weighted avg       0.99      0.99      0.99      1146

