In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv('Salary_Data.csv')

In [6]:
df.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [8]:
df.shape

(30, 2)

In [9]:
x = df['YearsExperience']

In [10]:
x

0      1.1
1      1.3
2      1.5
3      2.0
4      2.2
5      2.9
6      3.0
7      3.2
8      3.2
9      3.7
10     3.9
11     4.0
12     4.0
13     4.1
14     4.5
15     4.9
16     5.1
17     5.3
18     5.9
19     6.0
20     6.8
21     7.1
22     7.9
23     8.2
24     8.7
25     9.0
26     9.5
27     9.6
28    10.3
29    10.5
Name: YearsExperience, dtype: float64

In [11]:
y = df['Salary']

In [12]:
y 

0      39343.0
1      46205.0
2      37731.0
3      43525.0
4      39891.0
5      56642.0
6      60150.0
7      54445.0
8      64445.0
9      57189.0
10     63218.0
11     55794.0
12     56957.0
13     57081.0
14     61111.0
15     67938.0
16     66029.0
17     83088.0
18     81363.0
19     93940.0
20     91738.0
21     98273.0
22    101302.0
23    113812.0
24    109431.0
25    105582.0
26    116969.0
27    112635.0
28    122391.0
29    121872.0
Name: Salary, dtype: float64

In [15]:
from sklearn.model_selection import train_test_split

In [23]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = .30,random_state=42)

In [28]:
xtrain_ = [ 1.1 , 2.2  ,5.1 , 2.9,  4.1 , 4.   ,7.9 , 1.3,  1.5,  9,   2,   7.1,  9.5,  5.9,
 10.6,  6.8 , 3.2,  3.9,  4.5,  6.6,   3.7 ]

In [29]:
xtrain = np.array(xtrain_).reshape(-1,1)

In [30]:
xtrain

array([[ 1.1],
       [ 2.2],
       [ 5.1],
       [ 2.9],
       [ 4.1],
       [ 4. ],
       [ 7.9],
       [ 1.3],
       [ 1.5],
       [ 9. ],
       [ 2. ],
       [ 7.1],
       [ 9.5],
       [ 5.9],
       [10.6],
       [ 6.8],
       [ 3.2],
       [ 3.9],
       [ 4.5],
       [ 6.6],
       [ 3.7]])

In [36]:
xtest_ = [ 9.6 , 4.9 , 8.2 , 5.3,  3.2,  3.7, 10.3,  8.7, 4.4 ]

In [37]:
xtest = np.array(xtest_).reshape(-1,1)

In [38]:
from sklearn.linear_model import LinearRegression

In [39]:
model = LinearRegression()

In [40]:
model.fit(xtrain,ytrain)

LinearRegression()

In [41]:
model.predict(xtest)

array([115080.19798018,  71057.33333333, 101967.00425559,  74803.96011179,
        55134.1695249 ,  59817.45299797, 121636.79484248, 106650.28772866,
        66374.04986026])

In [42]:
model.score(xtest,ytest)

0.9285054374629911

In [43]:
from sklearn.metrics import mean_squared_error,r2_score

In [44]:
pred = model.predict(xtest)

In [45]:
pred

array([115080.19798018,  71057.33333333, 101967.00425559,  74803.96011179,
        55134.1695249 ,  59817.45299797, 121636.79484248, 106650.28772866,
        66374.04986026])

In [46]:
r2_score(ytest,pred)

0.9285054374629911

In [49]:
mean_squared_error(pred,ytest)

46135646.46513827